apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbita-ingress
  namespace: orbita
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: orbita-api
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: orbita.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: orbita-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbita-frontend
                port:
                  number: 80
